version: '2'
services:
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - db-data:/data/db
        ports:
          - 27017:27017
volumes:
  db-data: